<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Create Task' => 'Créer un tâche',
    'Create User' => 'Créer un utilisateur',
    'Create User Task' => '',
    'Delete' => 'Supprimer',
	'Order' => 'Ordre',
	'Order ID' => 'Ordre',
    'Projects can be moved :' => 'Les projets peuvent être déplacés',
    'Reset' => 'Réinitialiser',
    'Save' => 'Sauvergarder',
    'Search' => 'Rechercher',
    'Task Creator' => 'Créateur ',
    'Task Description' => 'Description ',
    'Task Emergency' => 'Urgence ',
    'Task End' => 'Fin ',
    'Task ID' => 'ID',
    'Task Limit' => 'Limite',
    'Task Name' => 'Nom',
    'Task Parent' => 'Tâche parente',
    'Task Priority' => 'Priorité ',
    'Task Status' => 'Statut ',
    'Tasks' => 'Tâches',
    'Tasks can be moved :' => 'Les tâches peuvent être déplacées',
    'The requested page does not exist.' => '',
    'Update' => 'Mettre à jour',
    'Update Task: mode' => '',
    'Update User Task: mode' => '',
    'Update User: mode' => '',
    'User First Name' => 'Prénom',
    'User ID' => 'ID',
    'User Login' => 'Identifiant',
    'User Name' => 'Nom',
    'User Password' => 'Mot de passe',
    'User Role' => 'Rôle',
    'User Task Order' => 'Ordre',
    'User Task Task' => 'Tâche',
    'User Task User' => 'Utilisateur',
    'User Tasks' => 'Tâches',
    'User Type' => 'Type',
    'Users' => 'Utilisateurs',
];
